services:
#Redis database
  redis-server:
    image: redis
    volumes:
      - ./redis:/data
    command: ["redis-server", "--protected-mode", "no"]
    #Node Application
  node-app:
     build: ./
     image: docker.io/geethakakani/visits
     ports:
        - "8081:8081"
